from decouple import config

CONNECTION_DATABASE = config('CONNECTION_DATABASE')
BCRYPT_SALT_ROUNDS = 12
MAX_WORD_LENGTH = 64
TOKEN_EXPIRATION = 5 * 60

PRIVATE_KEY_PATH = config('PRIVATE_KEY_PATH')
PUBLIC_KEY_PATH = config('PUBLIC_KEY_PATH')
PRIVATE_KEY_PASSWORD = config('PRIVATE_KEY_PASSWORD')
SENDER_EMAIL = config('SENDER_EMAIL')
APP_PASSWORD = config('APP_PASSWORD')